### PR TITLE
Optional insert mode keys

### PR DESCRIPTION
**Pull request by kba**
Insert mode mapping with `<Leader>` can be annoying, because they create a lag whenever `<Leader>` is pressed and fire when they weren't meant to fire (e.g. editing CSV).

### CODE REVIEW

**Comment by vitalk** [comment]
Hello @kba!

You already can disable all key bindings defined by plugin via `g:simple_todo_map_keys`, and then bind only required one. Why do you need another option?

**Comment by kba** [comment]
Because having the insert mode mappings with `<Leader>` active means that vim starts checking for a mapping whenever `<Leader>` is pressed. I have set `<Leader>` to comma, so there is always a slight lag after pressing `,` until vim knows whether it should insert the keys or execute the mapping. 

Since the plugin is globally active, the mappings could fire when they shouldn't, e.g. if one is editing CSV data, writing `,i`, `,o`, `,O` is not meant to create TODO items. Same with arguments to functions, i.e. `myFunc(x,i);`. If the `<Leader>` is set to `\`, the plugin fires e.g. when using octal escapes in Perl (`my $var = "\o{120}".

@zxiest removed the mappings outright, see https://github.com/zxiest/vim-simple-todo/commit/865de6dfb47b4e1ac94bebd45027c90705d204ac.

**Comment by vitalk** [comment]
Why do you not disable all key bindings and bind only required in your `.vimrc`? Something like this:

```viml
let g:simple_todo_map_keys = 0
nmap <silent><Leader>i <Plug>(simple-todo-new)
nmap <silent><Leader>I <Plug>(simple-todo-new-start-of-line)
vmap <silent><Leader>I <Plug>(simple-todo-new-start-of-line)
nmap <silent><Leader>o <Plug>(simple-todo-below)
nmap <silent><Leader>O <Plug>(simple-todo-above)
nmap <silent><Leader>x <Plug>(simple-todo-mark-as-done)
vmap <silent><Leader>x <Plug>(simple-todo-mark-as-done)
nmap <silent><Leader>X <Plug>(simple-todo-mark-as-undone)
vmap <silent><Leader>X <Plug>(simple-todo-mark-as-undone)
```

**Comment by kba** [comment]
Now I understand. Yes, that works as well, it's just more verbose (10 lines vs 1 line) and requires understanding of simple-todo's API and changes to the vimrc if the API is going to change, e.g. the `simple-todo-new-start-of-line` will not be enabled for users who enabled all but the insert mode mappings in the past with your method.

On the other hand, verbosity can be a good thing (no surprising changes of mapping or unwanted new features). If you think that this option is too specific, feel free to close the PR.

**Comment by vitalk** [comment]
I prefer to keep plugin API clear and simple, so I close this pull request. Thank you anyway.

**Comment by mlovic** [comment]
For what it's worth, I would also be strongly in favor of an `insert_mode_mappings` option. I have `leader` set to `<space>` (a configuration I feel is quite common), which makes the plugin almost unusable without copying 10 lines from the source to my `.vimrc`.

**Comment by vitalk** [comment]
This feature is more required then I expected, so now default key bindings can disabled for each mode separately

```viml
let g:simple_todo_map_normal_mode_keys = 0
let g:simple_todo_map_insert_mode_keys = 0
let g:simple_todo_map_visual_mode_keys = 0
```

Thanks @mlovic and @kba!

**Comment by mlovic** [comment]
Looks great! Thank you @vitalk

**Pull request closed without merging**
